image: ubuntu1804

version: 0.2.3.{build}

environment:
    ARTIFACT: build/pixel32-v$(APPVEYOR_BUILD_VERSION).img

services:
    - docker

branches:
  only:
    - master

build_script:
    - docker run -v ${APPVEYOR_BUILD_FOLDER}/build:/build murilopolese/pixel32-build:latest

after_build:
    - sh: sudo mv build/pixel32.img $ARTIFACT

artifacts:
    - path: $(ARTIFACT)

deploy:
    release: v$(APPVEYOR_BUILD_VERSION)
    description: $(APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED)
    provider: GitHub
    auth_token:
        secure: MkcLF/KRxO+M0R+3Bav0L1n64zGja1dx1HvTxv+UaHD5kmJT6lnQp0BGWjXYX77O
    artifact: $(ARTIFACT)
    draft: true
    on:
        branch: master
